export interface DogListing {
  id: string
  name: string
  age: string
  breed: string
  location: string
  state: string
  zip: string
  description: string
  shortDescription: string
  photoCount: number
  videoCount: number
  verified: boolean
  availableNow: boolean
  category: "puppy" | "adult" | "rescue" | "breeder"
  gender: "male" | "female"
  price: string
  phone: string
  language: string
  size: string
  color: string
  temperament: string
  postedAt: string
}

export const sampleDogs: DogListing[] = [
  {
    id: "1",
    name: "Bella",
    age: "8 weeks",
    breed: "Golden Retriever",
    location: "Austin",
    state: "TX",
    zip: "78701",
    description: "Beautiful Golden Retriever puppy from a loving family. Fully vaccinated, dewormed, and comes with AKC registration papers. Both parents are on site and health tested. Bella is incredibly friendly, loves to play, and has been raised around children. She will be a wonderful addition to any family looking for a loyal companion.",
    shortDescription: "Beautiful Golden Retriever puppy, fully vaccinated and AKC registered.",
    photoCount: 6,
    videoCount: 1,
    verified: true,
    availableNow: true,
    category: "puppy",
    gender: "female",
    price: "$1,200",
    phone: "15125551234",
    language: "English",
    size: "Large (expected 55-75 lbs)",
    color: "Golden",
    temperament: "Friendly, Playful, Loyal",
    postedAt: "2 hours ago",
  },
  {
    id: "2",
    name: "Max",
    age: "2 years",
    breed: "German Shepherd",
    location: "Los Angeles",
    state: "CA",
    zip: "90001",
    description: "Max is a well-trained German Shepherd looking for an active home. He knows basic commands (sit, stay, come, heel) and is great on a leash. He is protective yet gentle and loves long walks and hikes. He has been neutered and is up to date on all vaccinations. Would do best in a home with a yard.",
    shortDescription: "Well-trained German Shepherd, knows commands, great with active families.",
    photoCount: 4,
    videoCount: 0,
    verified: true,
    availableNow: true,
    category: "adult",
    gender: "male",
    price: "$800",
    phone: "12145559876",
    language: "English",
    size: "Large (85 lbs)",
    color: "Black and Tan",
    temperament: "Protective, Intelligent, Active",
    postedAt: "5 hours ago",
  },
  {
    id: "3",
    name: "Daisy",
    age: "1 year",
    breed: "Labrador Retriever",
    location: "Miami",
    state: "FL",
    zip: "33101",
    description: "Sweet Labrador rescue from a local shelter. Daisy is spayed, microchipped, and current on all shots. She was found as a stray but has adjusted wonderfully to home life. She is gentle, house-trained, and loves belly rubs. Looking for a forever family who will give her the love she deserves.",
    shortDescription: "Sweet Labrador rescue, spayed and microchipped, house-trained.",
    photoCount: 3,
    videoCount: 0,
    verified: false,
    availableNow: true,
    category: "rescue",
    gender: "female",
    price: "Adoption Fee: $150",
    phone: "17135554567",
    language: "English",
    size: "Large (65 lbs)",
    color: "Chocolate",
    temperament: "Gentle, Loving, Calm",
    postedAt: "1 day ago",
  },
  {
    id: "4",
    name: "Rocky",
    age: "12 weeks",
    breed: "French Bulldog",
    location: "New York",
    state: "NY",
    zip: "10001",
    description: "Adorable Frenchie puppy available from a reputable breeder. Rocky has a champion bloodline, comes with full health guarantee, first set of vaccinations, and microchip. He is a compact little guy with big bat ears and a hilarious personality. Perfect for apartment living.",
    shortDescription: "Adorable Frenchie puppy, champion bloodline, health guaranteed.",
    photoCount: 6,
    videoCount: 2,
    verified: true,
    availableNow: false,
    category: "breeder",
    gender: "male",
    price: "$3,500",
    phone: "12105558765",
    language: "English",
    size: "Small (expected 20-28 lbs)",
    color: "Fawn with Black Mask",
    temperament: "Playful, Affectionate, Easygoing",
    postedAt: "3 hours ago",
  },
  {
    id: "5",
    name: "Luna",
    age: "6 months",
    breed: "Husky",
    location: "Denver",
    state: "CO",
    zip: "80201",
    description: "Luna is a striking Husky with beautiful blue eyes. She is energetic, loves the outdoors, and gets along well with other dogs. She has been crate-trained and is learning basic commands. Would thrive with an active owner who enjoys running or hiking. Comes with vaccination records.",
    shortDescription: "Striking blue-eyed Husky, energetic and great with other dogs.",
    photoCount: 5,
    videoCount: 1,
    verified: true,
    availableNow: true,
    category: "puppy",
    gender: "female",
    price: "$950",
    phone: "19725553210",
    language: "English",
    size: "Medium-Large (expected 35-50 lbs)",
    color: "Gray and White",
    temperament: "Energetic, Social, Adventurous",
    postedAt: "8 hours ago",
  },
  {
    id: "6",
    name: "Cooper",
    age: "3 years",
    breed: "Beagle",
    location: "Chicago",
    state: "IL",
    zip: "60601",
    description: "Cooper is a sweet and mellow Beagle who loves naps on the couch and exploring the backyard. He is great with children and cats. He has been neutered and is fully vaccinated. His previous owner relocated and could not take him. Looking for a calm, loving home.",
    shortDescription: "Sweet Beagle, great with kids and cats, calm temperament.",
    photoCount: 3,
    videoCount: 0,
    verified: false,
    availableNow: true,
    category: "adult",
    gender: "male",
    price: "$400",
    phone: "18175556543",
    language: "English",
    size: "Medium (30 lbs)",
    color: "Tri-color",
    temperament: "Gentle, Curious, Mellow",
    postedAt: "2 days ago",
  },
  {
    id: "7",
    name: "Rosie",
    age: "10 weeks",
    breed: "Poodle (Standard)",
    location: "Seattle",
    state: "WA",
    zip: "98101",
    description: "Rosie is a hypoallergenic Standard Poodle puppy, perfect for families with allergies. She comes from health-tested parents, has her first vaccinations, and is being raised in a family environment. She is intelligent, eager to please, and will excel in obedience training.",
    shortDescription: "Hypoallergenic Poodle puppy, health-tested parents, great for allergies.",
    photoCount: 4,
    videoCount: 1,
    verified: true,
    availableNow: true,
    category: "breeder",
    gender: "female",
    price: "$2,000",
    phone: "19725559090",
    language: "English",
    size: "Large (expected 45-65 lbs)",
    color: "Apricot",
    temperament: "Intelligent, Eager, Graceful",
    postedAt: "6 hours ago",
  },
  {
    id: "8",
    name: "Buddy",
    age: "4 years",
    breed: "Mixed Breed",
    location: "Atlanta",
    state: "GA",
    zip: "30301",
    description: "Buddy is a lovable mixed breed rescue who was saved from a high-kill shelter. He weighs about 40 lbs and appears to be a Lab/Terrier mix. He is neutered, vaccinated, and microchipped. He is the sweetest boy who just wants to be near his person. Ideal for someone looking for a calm companion.",
    shortDescription: "Lovable Lab/Terrier mix rescue, calm companion, fully vetted.",
    photoCount: 2,
    videoCount: 0,
    verified: false,
    availableNow: true,
    category: "rescue",
    gender: "male",
    price: "Adoption Fee: $100",
    phone: "18175552345",
    language: "English",
    size: "Medium (40 lbs)",
    color: "Brown and White",
    temperament: "Calm, Affectionate, Loyal",
    postedAt: "4 days ago",
  },
  {
    id: "9",
    name: "Coco",
    age: "14 weeks",
    breed: "Dachshund",
    location: "Phoenix",
    state: "AZ",
    zip: "85001",
    description: "Coco is a miniature Dachshund with a smooth coat and endless energy. She is a little firecracker who loves to burrow under blankets and chase toys. She comes with her first set of shots, deworming, and a health guarantee. Great for apartment or condo living.",
    shortDescription: "Miniature Dachshund, smooth coat, full of personality.",
    photoCount: 5,
    videoCount: 0,
    verified: true,
    availableNow: true,
    category: "puppy",
    gender: "female",
    price: "$1,100",
    phone: "14695558888",
    language: "English",
    size: "Small (expected 8-11 lbs)",
    color: "Red",
    temperament: "Bold, Curious, Lively",
    postedAt: "1 day ago",
  },
  {
    id: "10",
    name: "Duke",
    age: "5 months",
    breed: "Golden Retriever",
    location: "Nashville",
    state: "TN",
    zip: "37201",
    description: "Duke is a gorgeous Golden Retriever puppy with a luxurious coat and the sweetest disposition. He is being raised in our home with kids and other dogs. Comes with full AKC papers, health guarantee, and his first round of vaccinations. He loves car rides and swimming.",
    shortDescription: "Gorgeous Golden puppy, AKC registered, loves kids and other dogs.",
    photoCount: 6,
    videoCount: 1,
    verified: true,
    availableNow: true,
    category: "breeder",
    gender: "male",
    price: "$1,500",
    phone: "16155559999",
    language: "English",
    size: "Large (expected 65-75 lbs)",
    color: "Dark Golden",
    temperament: "Gentle, Obedient, Social",
    postedAt: "4 hours ago",
  },
  {
    id: "11",
    name: "Sadie",
    age: "2 years",
    breed: "Labrador Retriever",
    location: "Boston",
    state: "MA",
    zip: "02101",
    description: "Sadie is a beautiful yellow Lab who needs a new home due to her owner's relocation overseas. She is fully trained, great on leash, and absolutely loves fetch. She is spayed, up to date on all vaccinations, and has no health issues. Would do great in a family with kids.",
    shortDescription: "Beautiful yellow Lab, fully trained, great with families.",
    photoCount: 4,
    videoCount: 0,
    verified: true,
    availableNow: true,
    category: "adult",
    gender: "female",
    price: "$600",
    phone: "16175553333",
    language: "English",
    size: "Large (62 lbs)",
    color: "Yellow",
    temperament: "Friendly, Energetic, Loyal",
    postedAt: "12 hours ago",
  },
  {
    id: "12",
    name: "Bear",
    age: "9 weeks",
    breed: "German Shepherd",
    location: "Portland",
    state: "OR",
    zip: "97201",
    description: "Bear is a strong, healthy German Shepherd puppy from working line parents. Both parents have OFA certified hips and elbows. He will be an excellent family protector and companion. Comes with first vaccinations, deworming, microchip, and a 2-year health guarantee.",
    shortDescription: "Working line GSD puppy, OFA certified parents, health guaranteed.",
    photoCount: 5,
    videoCount: 2,
    verified: true,
    availableNow: false,
    category: "breeder",
    gender: "male",
    price: "$2,200",
    phone: "15035557777",
    language: "English",
    size: "Large (expected 75-90 lbs)",
    color: "Sable",
    temperament: "Confident, Loyal, Trainable",
    postedAt: "1 day ago",
  },
  {
    id: "13",
    name: "Penny",
    age: "3 years",
    breed: "Beagle",
    location: "Minneapolis",
    state: "MN",
    zip: "55401",
    description: "Penny is a sweet rescue Beagle found wandering near a highway. She has been nursed back to health, spayed, vaccinated, and is now looking for her forever home. She is gentle with everyone she meets and has a nose for adventure. Great apartment dog.",
    shortDescription: "Sweet rescue Beagle, gentle with everyone, loves adventure.",
    photoCount: 3,
    videoCount: 0,
    verified: false,
    availableNow: true,
    category: "rescue",
    gender: "female",
    price: "Adoption Fee: $175",
    phone: "16125554444",
    language: "English",
    size: "Medium (25 lbs)",
    color: "Lemon and White",
    temperament: "Sweet, Curious, Gentle",
    postedAt: "3 days ago",
  },
  {
    id: "14",
    name: "Zeus",
    age: "10 weeks",
    breed: "Husky",
    location: "Anchorage",
    state: "AK",
    zip: "99501",
    description: "Zeus is a stunning purebred Siberian Husky puppy with one blue and one brown eye. He is incredibly playful and already showing a lot of personality. Both parents are AKC registered and can be seen on premises. Comes with health check, first vaccinations, and deworming.",
    shortDescription: "Stunning Husky puppy with heterochromia, AKC parents on site.",
    photoCount: 6,
    videoCount: 1,
    verified: true,
    availableNow: true,
    category: "puppy",
    gender: "male",
    price: "$1,300",
    phone: "19075551111",
    language: "English",
    size: "Large (expected 45-60 lbs)",
    color: "Black and White",
    temperament: "Playful, Energetic, Vocal",
    postedAt: "7 hours ago",
  },
  {
    id: "15",
    name: "Maple",
    age: "5 years",
    breed: "Mixed Breed",
    location: "Raleigh",
    state: "NC",
    zip: "27601",
    description: "Maple is a gentle Pit Bull/Lab mix who was surrendered when her family could no longer care for her. She is house-trained, crate-trained, and does well on a leash. She is spayed, microchipped, and current on all shots. She loves belly rubs and is a certified couch potato.",
    shortDescription: "Gentle Pit/Lab mix, house-trained, loves belly rubs and couch time.",
    photoCount: 4,
    videoCount: 0,
    verified: false,
    availableNow: true,
    category: "rescue",
    gender: "female",
    price: "Adoption Fee: $125",
    phone: "19195552222",
    language: "English",
    size: "Medium (45 lbs)",
    color: "Brindle",
    temperament: "Gentle, Calm, Affectionate",
    postedAt: "5 days ago",
  },
]
